<?php
/**
 * Copyright © Ronangr1, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

/**
 * @var \Ronangr1\CmsImportExport\Block\Adminhtml\Import $block
 * @var \Magento\Framework\Escaper $escaper
 */

$entityType = $block->getData('entity_type');
?>

<div class="admin__page-section">
    <form id="cms-import-form" enctype="multipart/form-data">
        <div class="admin__field">
            <label class="admin__field-label" for="import_file"><?= __('Select ZIP file') ?></label>
            <div class="admin__field-control">
                <input type="file" id="import_file" name="import_file" accept=".zip"/>
            </div>
        </div>
        <div class="admin__field">
            OR
        </div>
        <div
            id="drop_zone"
            ondrop="dropHandler(event);"
            ondragover="dragOverHandler(event);">
            <p>
                <?= $escaper->escapeHtml(__('Drag one or more files to this <i>drop zone</i>'), ['i']) ?>
            </p>
        </div>
        <div class="admin__actions">
            <button type="button" id="cms-import-submit" class="action-primary">
                <span><?= $escaper->escapeHtml(__('Import')) ?></span>
            </button>
        </div>
        <input type="hidden" name="entity_type" value="<?= $escaper->escapeHtmlAttr($entityType) ?>"
        <input type="hidden" name="form_key" value="<?= $escaper->escapeHtmlAttr($block->getFormKey()) ?>"
    </form>
    <div id="cms-import-result"></div>
</div>

<script type="text/x-magento-init">
    {
        "#cms-import-form": {
            "cmsAjaxImport": {
                "actionUrl": "<?= $escaper->escapeUrl($block->getActionUrl()) ?>",
                "entityType": "<?= $escaper->escapeHtml($entityType) ?>"
        }
    }
}
</script>
